# Generated by Django 5.0.4 on 2024-05-14 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
